spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource: 
    url: jdbc:mariadb://localhost:3306/mnscdb
    username: mnsc
    password: mnsc
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace